### ISSUE TITLE
Deprecate the project in favor of "mautrix-telegram"?

### ISSUE THREAD

**Issue by Hi-Angel** [matrix-org/matrix-appservice-tg#17]
It seems the current project is unmaintained: nobody answers to issues, accepts PRs, and last code commit was 2 years ago despite having [glaring though trivial to fix issues](https://github.com/matrix-org/matrix-appservice-tg/issues/13).

[mautrix-telegram](https://github.com/tulir/mautrix-telegram) on the other hand seems to be actively developed, and I wonder if it makes sense to deprecate this project in preference of that one.

**Comment by jaywink** [comment]
Done via #15
